### ISSUE TITLE
Huge RAM Usage

### ISSUE THREAD

**Issue by DontGoToCollege** [xanasoft/MajorPrivacy#15] opened 2024-08-05 13:18 UTC
Note: I didnt update the name of my folder from v 90 to v 95 but with the latest version I'm experiencing a lot of RAM usage while casually watching Youtube videos.

Not sure what could be the cause but wanted to reach out.

![image](https://github.com/user-attachments/assets/00b25e61-d42c-42e7-8672-4d753915b1c9)

**Comment by DavidXanatos** [comment] 2024-08-05 16:04
duplicate of https://github.com/xanasoft/MajorPrivacy/issues/12
We need to add a mechanism to smartly drop log entries, currently logging all file access for an hour seams to long and the memory usage is to high.

**Comment by DavidXanatos** [comment] 2024-11-01 12:07
try: https://github.com/xanasoft/MajorPrivacy/releases/tag/v0.96.0

**Closed by DavidXanatos** 2024-11-01 12:07 UTC
