### ISSUE TITLE
Service ABI Mismatch and v0.95.0 in latest download instead of v.0.96.0

### ISSUE THREAD

**Issue by DontGoToCollege** [xanasoft/MajorPrivacy#17] opened 2024-11-01 12:45 UTC
Might just be a me issue with the latest version

![image](https://github.com/user-attachments/assets/99324db9-d2aa-4bd9-8427-a88aa9c8bf59)
![image](https://github.com/user-attachments/assets/8a45cd3b-a22d-4e05-b1c9-e6750d873ad1)

**Comment by DavidXanatos** [comment] 2024-11-03 20:33
The driver has an issue with windows 10 a new build will be released soon with a win 10 compatible driver.

**Comment by DavidXanatos** [comment] 2024-11-13 07:17
0.96.1 is out please try it

**Comment by DavidXanatos** [comment] 2024-11-13 13:54
this is strange i tested it on a new win 10 VM build 19045.5011
which windows 10 version are you trying on?
also whats the path you unpacked the zip to?

**Comment by DavidXanatos** [comment] 2024-11-13 17:42
Please try starting MajorPrivacy.exe as administrator

**Comment by DavidXanatos** [comment] 2024-11-13 17:54
hmm... did you reboot the PC in the mean time?
if not the try ```net stop KernelIsolator```
I have seen this behavior today once when testing but it was not reproducible it was gone after I unloaded and then re loaded the driver and did not come back.

**Comment by DavidXanatos** [comment] 2024-11-15 07:36
I have managed to replicate the failure mode I observed earlier,
it was caused by a older version of the driver still being installed.
try running ```sc delete KernelIsolator``` bevore starting the new MP build, if it returns an error first run ```net stop KernelIsolator```
I'll add a fix in the next build which when starting up checks for previouse driver versions being present and removes them automatically

**Comment by DavidXanatos** [comment] 2024-12-01 09:03
fixed in 0.96.2 it now checks the driver path and if needed re installs the latest driver version

**Closed by DavidXanatos** 2024-12-01 09:03 UTC
